name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Actualizado a v4
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Actualizado a v4 para corregir el error
        with:
          name: MiCalculadoraAPK
          path: build/app/outputs/flutter-apk/app-release.apk
